// Mapas del mundo. Leyenda de tiles:
//  Muros: T árbol, B edificio, D puerta, F valla, W agua, X pared interior,
//         L estantería, K mostrador
//  Suelos: . camino, , hierba alta (encuentros), : flores, - suelo interior,
//          m alfombra de salida, e salida por borde
// Los warps se indexan por "x,y". NPCs con cond(flags) opcional y script por nombre.

const MAPS = {

  pallet: {
    name: 'PUEBLO PALETA',
    outdoor: true,
    grid: [
      'TTTTTTTeeTTTTTTTTT',
      'T................T',
      'T.BBBB.....BBBB..T',
      'T.BDBB.....BBDB..T',
      'T................T',
      'T....::....::....T',
      'T.BBBBBB.........T',
      'T.BBBDBB...::....T',
      'T..........WWWW..T',
      'T...::.....WWWW..T',
      'T................T',
      'TTTTTTTTTTTTTTTTTT',
    ],
    warps: {
      '7,0': { to: 'route1', x: 5.5, y: 21.5, ang: -Math.PI / 2 },
      '8,0': { to: 'route1', x: 6.5, y: 21.5, ang: -Math.PI / 2 },
      '3,3': { to: 'home', x: 4.5, y: 4.2, ang: -Math.PI / 2 },
      '13,3': { locked: 'Está cerrado con llave...' },
      '5,7': { to: 'lab', x: 5.5, y: 6.5, ang: -Math.PI / 2 },
    },
    encounters: null,
    npcs: [
      { x: 6.5, y: 1.4, sprite: 'OAK', cond: f => !f.hasPikachu, script: 'oakBlock' },
      { x: 8.5, y: 4.5, sprite: 'SIGN', lines: ['PUEBLO PALETA', 'Un lugar tranquilo de tonos puros.'] },
      { x: 2.5, y: 4.7, sprite: 'SIGN', lines: ['CASA DE ROJO'],
        dark: ['CASA DE R███', 'Aquí no vive nadie', 'desde 1996.'] },
      { x: 3.5, y: 8.5, sprite: 'SIGN', lines: ['LABORATORIO POKéMON DE OAK'],
        dark: ['CONSULTA 2', 'DR. OAK - PSIQUIATRÍA INFANTIL'] },
      { x: 11.5, y: 5.5, sprite: 'GIRL', lines: ['¡La tecnología es increíble!', 'Ahora el mundo se ve en 3D y en', 'primera persona.'],
        dark: ['Aquí nunca anochece.', '¿Te has fijado?', 'Nunca. Anochece.'] },
    ],
  },

  route1: {
    name: 'RUTA 1',
    outdoor: true,
    grid: [
      'TTTTTeeTTTTT',
      'T..........T',
      'T.,,,,.....T',
      'T.,,,,.TT..T',
      'T......TT..T',
      'T..,,,,,...T',
      'T..,,,,,...T',
      'T.....,,...T',
      'T.TT.......T',
      'T.TT..,,,..T',
      'T.....,,,..T',
      'T..,,..,...T',
      'T..,,......T',
      'T..........T',
      'T.,,,,,,...T',
      'T.,,,,,,.T.T',
      'T........T.T',
      'T..TT......T',
      'T..TT.,,,..T',
      'T.....,,,..T',
      'T.....,,,..T',
      'T..........T',
      'T..........T',
      'TTTTTeeTTTTT',
    ],
    warps: {
      '5,0': { to: 'viridian', x: 5.5, y: 12.5, ang: -Math.PI / 2 },
      '6,0': { to: 'viridian', x: 6.5, y: 12.5, ang: -Math.PI / 2 },
      '5,23': { to: 'pallet', x: 7.5, y: 1.6, ang: Math.PI / 2 },
      '6,23': { to: 'pallet', x: 8.5, y: 1.6, ang: Math.PI / 2 },
    },
    encounters: {
      lv: [2, 5],
      table: [['PIDGEY', 32], ['RATTATA', 32], ['CATERPIE', 14], ['WEEDLE', 12], ['SPEAROW', 6], ['NIDORANM', 3], ['ODDISH', 1]],
    },
    npcs: [
      { x: 8.5, y: 12.5, sprite: 'BOY', lines: ['¡Eh! Llevas POKéMON, ¿verdad?', 'La hierba alta está llena de', 'POKéMON salvajes.'],
        dark: ['¿Oyes la hierba?', 'No es el viento.', 'Son ellos, que respiran', 'bajito para que no los oigas.'] },
      { x: 3.5, y: 21.5, sprite: 'SIGN', lines: ['RUTA 1', 'PUEBLO PALETA - CIUDAD VERDE'] },
    ],
  },

  viridian: {
    name: 'CIUDAD VERDE',
    outdoor: true,
    grid: [
      'TTTTTTTTTeeTTTTTTTTT',
      'T..................T',
      'T..BBBB....BBBB....T',
      'T..BDBB....BBDB....T',
      'T..................T',
      'T.,,,......::......T',
      'T.,,,..............T',
      'T.,,,....WWW.......T',
      'T........WWW...FF..T',
      'T..................T',
      'T..::........::....T',
      'T..................T',
      'T..................T',
      'TTTTTeeTTTTTTTTTTTTT',
    ],
    warps: {
      '4,3': { to: 'center', x: 5.5, y: 4.5, ang: -Math.PI / 2 },
      '13,3': { to: 'mart', x: 5.5, y: 4.5, ang: -Math.PI / 2 },
      '5,13': { to: 'route1', x: 5.5, y: 1.6, ang: Math.PI / 2 },
      '6,13': { to: 'route1', x: 6.5, y: 1.6, ang: Math.PI / 2 },
      '9,0': { to: 'forest', x: 5.5, y: 22.5, ang: -Math.PI / 2 },
      '10,0': { to: 'forest', x: 6.5, y: 22.5, ang: -Math.PI / 2 },
    },
    encounters: {
      lv: [3, 6],
      table: [['PIDGEY', 30], ['RATTATA', 30], ['MANKEY', 20], ['SPEAROW', 12], ['ODDISH', 8]],
      onlyGrass: true,
    },
    npcs: [
      { x: 5.5, y: 4.6, sprite: 'SIGN', lines: ['CENTRO POKéMON', 'Curamos a tus POKéMON.'] },
      { x: 14.5, y: 4.6, sprite: 'SIGN', lines: ['TIENDA POKéMON', 'Todo para tu aventura.'] },
      { x: 9.5, y: 10.5, sprite: 'BOY', lines: ['El GIMNASIO está al norte.', 'En CIUDAD PLATEADA.', 'Cruza el BOSQUE VERDE.'],
        dark: ['El GIMNASIO no está cerrado.', 'Es que no existe.', 'Casi nada de esto existe.'] },
      { x: 16.5, y: 9.5, sprite: 'GIRL', lines: ['CIUDAD VERDE,', 'la ciudad de la eterna', 'naturaleza verde.'],
        dark: ['Te he visto antes.', 'Atado a la camilla del', 'ala este.', 'Saludabas con la mano.'] },
      { x: 9.5, y: 1.5, sprite: 'SIGN', lines: ['RUTA 2', 'BOSQUE VERDE → CIUDAD PLATEADA'] },
    ],
  },

  home: {
    name: 'TU CASA',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXX',
      'XLL-X-----LLX',
      'XLL-X------IX',
      'X---X------IX',
      'X-----------X',
      'X-----------X',
      'X-----------X',
      'XXXXXXmXXXXXX',
    ],
    warps: { '6,7': { to: 'pallet', x: 3.5, y: 4.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 2.5, y: 3.5, sprite: 'MOM', script: 'mom' },
      { x: 10.5, y: 3.5, sprite: 'TV', script: 'homeTV' },
      { x: 7.5, y: 3.5, sprite: 'TABLE', script: 'homeTable' },
      { x: 5.5, y: 4.5, sprite: 'PLANT', lines: ['Una planta en una maceta.', 'Sus hojas están un poco amarillas.'],
        dark: ['La planta está muerta.', 'Lleva meses sin agua.'] },
    ],
  },

  lab: {
    name: 'LAB. POKéMON',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXXXX',
      'XLLLL---XLLLLLX',
      'XLLLL---XLLLLLX',
      'X------X------X',
      'X------X------X',
      'X.............X',
      'X.............X',
      'X.............X',
      'XXXXXXXmXXXXXXX',
    ],
    warps: { '7,8': { to: 'pallet', x: 5.5, y: 8.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 7.5, y: 1.7, sprite: 'OAK', script: 'oakLab' },
      { x: 10.5, y: 4.5, sprite: 'RIVAL', cond: f => f.hasPikachu && !f.rivalBeaten, script: 'rival' },
      { x: 2.5, y: 3.5, sprite: 'PC', lines: ['Máquinas con cables por todas', 'partes. Huele a plástico caliente.'],
        dark: ['Monitores apagados.', 'En uno se ve una línea plana.'] },
      { x: 12.5, y: 3.5, sprite: 'BOOKSHELF', lines: ['Estanterías llenas de libros', 'y Poké Balls vacías.'],
        dark: ['Carpetas con nombres.', 'La tuya es la más gruesa.'] },
    ],
  },

  center: {
    name: 'CENTRO POKéMON',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXXXXXX',
      'XKK...........KKX',
      'X...X.......X...X',
      'X...X.......X...X',
      'X...............X',
      'X...............X',
      'XXXXXXXmXXXXXXXXX',
    ],
    warps: { '7,6': { to: 'viridian', x: 4.5, y: 4.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 8.5, y: 1.3, sprite: 'NURSE', script: 'nurse' },
      { x: 3.5, y: 4.5, sprite: 'BOY', lines: ['Mis POKéMON quedaron como', 'nuevos. ¡La enfermera es genial!'],
        dark: ['Mis POKéMON duermen.', 'Aquí todos duermen.', 'Tú también deberías', 'volver a dormir.'] },
      { x: 13.5, y: 4.5, sprite: 'GIRL', lines: ['Estoy esperando a que curen', 'a mi RATTATA.', '¿Cuánto tardará?'],
        dark: ['Llevo aquí mucho tiempo.', 'Ya no me acuerdo por qué vine.'] },
      { x: 3.5, y: 2.5, sprite: 'HEALMACHINE', lines: ['Una máquina de curación.', 'Zumba suavemente.'],
        dark: ['La máquina tiene manchas.', 'No son de óxido.'] },
      { x: 13.5, y: 2.5, sprite: 'PHONE', lines: ['Un teléfono público.', 'Nadie llama nunca.'],
        dark: ['El teléfono está descolgado.', 'Se oye respirar al otro lado.'] },
    ],
  },

  mart: {
    name: 'TIENDA POKéMON',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXXXX',
      'XKKKK---XKKKKKX',
      'X-------X-----X',
      'X.............X',
      'X.............X',
      'X.............X',
      'XXXXXXXmXXXXXXX',
    ],
    warps: { '7,6': { to: 'viridian', x: 13.5, y: 4.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 4.5, y: 2.5, sprite: 'CLERK', script: 'clerk' },
      { x: 3.5, y: 3.5, sprite: 'BOY', lines: ['¡Aquí tienen de todo!', 'Desde Poké Balls', 'hasta Pociones.'],
        dark: ['¿Qué vas a hacer con eso?', '¿De verdad crees que sirve para algo?'] },
      { x: 11.5, y: 3.5, sprite: 'SHELF', lines: ['Estanterías con productos.', 'Los precios parecen razonables.'],
        dark: ['Cajas vacías en las estanterías.', 'Hay mucho polvo.', '¿Cuándo fue la última vez', 'que alguien compró algo aquí?'] },
    ],
  },
  forest: {
    name: 'BOSQUE VERDE',
    outdoor: true,
    grid: [
      'TTTTTeeTTTTTT',
      'T...........T',
      'T.,,,,,,....T',
      'T.,,,,,.TT..T',
      'T.......TT..T',
      'T.TT.,,,,,..T',
      'T.TT.,,,,,..T',
      'T...........T',
      'T.TT........T',
      'T.TT..,,,,..T',
      'T.....,,,,..T',
      'T..,,,.....TT',
      'T..,,,.....TT',
      'T...........T',
      'T.,,,,,....TT',
      'T.,,,,,..TT.T',
      'T........TT.T',
      'T...........T',
      'T.TT,,,,,,..T',
      'T.TT,,,,,,..T',
      'T...........T',
      'T.,,,,,.....T',
      'T...........T',
      'TTTTTeeTTTTTT',
    ],
    warps: {
      '5,0':  { to: 'route2', x: 5.5, y: 11.5, ang: -Math.PI / 2 },
      '6,0':  { to: 'route2', x: 6.5, y: 11.5, ang: -Math.PI / 2 },
      '5,23': { to: 'viridian', x: 9.5, y: 1.6, ang: Math.PI / 2 },
      '6,23': { to: 'viridian', x: 10.5, y: 1.6, ang: Math.PI / 2 },
    },
    encounters: {
      lv: [3, 7],
      table: [['CATERPIE', 35], ['WEEDLE', 25], ['PIDGEY', 20], ['METAPOD', 10], ['KAKUNA', 10]],
    },
    npcs: [
      { x: 5.5, y: 5.5, sprite: 'BOY', script: 'bugCatcher1' },
      { x: 5.5, y: 14.5, sprite: 'BOY', script: 'bugCatcher2' },
      { x: 6.5, y: 20.5, sprite: 'GIRL', script: 'forestLass' },
      { x: 6.5, y: 1.5, sprite: 'SIGN', lines: ['BOSQUE VERDE', 'CIUDAD VERDE ← → CIUDAD PLATEADA'] },
    ],
  },

  route2: {
    name: 'RUTA 2',
    outdoor: true,
    grid: [
      'TTTTTeeTTTTTT',
      'T...........T',
      'T.,,,,,.....T',
      'T.,,,,,..TT.T',
      'T........TT.T',
      'T...........T',
      'T...........T',
      'T...........T',
      'T.TT........T',
      'T.TT..,,,,..T',
      'T.....,,,,..T',
      'T...........T',
      'TTTTTeeTTTTTT',
    ],
    warps: {
      '5,0':  { to: 'pewter', x: 5.5, y: 10.5, ang: -Math.PI / 2 },
      '6,0':  { to: 'pewter', x: 6.5, y: 10.5, ang: -Math.PI / 2 },
      '5,12': { to: 'forest', x: 5.5, y: 1.5, ang: Math.PI / 2 },
      '6,12': { to: 'forest', x: 6.5, y: 1.5, ang: Math.PI / 2 },
    },
    encounters: {
      lv: [4, 8],
      table: [['PIDGEY', 30], ['RATTATA', 30], ['CATERPIE', 20], ['WEEDLE', 20]],
    },
    npcs: [
      { x: 3.5, y: 5.5, sprite: 'SIGN', lines: ['RUTA 2', 'CIUDAD VERDE ← CIUDAD PLATEADA →'] },
    ],
  },

  pewter: {
    name: 'CIUDAD PLATEADA',
    outdoor: true,
    grid: [
      'TTTTTeeTTTTTTT',
      'T............T',
      'T.BBBB..BBBB.T',
      'T.BDBB..BBDB.T',
      'T............T',
      'T.::.....:...T',
      'T.BBBBBB.....T',
      'T.BBDBBB.....T',
      'T............T',
      'T.FF.....FF..T',
      'T............T',
      'TTTTTeeTTTTTTT',
    ],
    warps: {
      '3,3':  { to: 'pewter_center', x: 5.5, y: 4.5, ang: -Math.PI / 2 },
      '10,3': { to: 'pewter_mart',   x: 5.5, y: 4.5, ang: -Math.PI / 2 },
      '4,7':  { to: 'gym',           x: 6.5, y: 7.5, ang: -Math.PI / 2 },
      '5,0':  { to: 'route3', x: 5.5, y: 18.5, ang: -Math.PI / 2 },
      '6,0':  { to: 'route3', x: 6.5, y: 18.5, ang: -Math.PI / 2 },
      '5,11': { to: 'route2', x: 5.5, y: 1.5, ang: Math.PI / 2 },
      '6,11': { to: 'route2', x: 6.5, y: 1.5, ang: Math.PI / 2 },
    },
    encounters: null,
    npcs: [
      { x: 4.5, y: 4.6, sprite: 'SIGN', lines: ['CENTRO POKéMON', 'Curamos a tus POKéMON.'] },
      { x: 10.5, y: 4.6, sprite: 'SIGN', lines: ['TIENDA POKéMON', 'Todo para tu aventura.'] },
      { x: 5.5, y: 8.6, sprite: 'SIGN', lines: ['GIMNASIO POKéMON', 'Líder: BROCK', 'Especialista en ROCA.'] },
      { x: 8.5, y: 1.5, sprite: 'BOY', script: 'pewterBoy' },
      { x: 11.5, y: 1.5, sprite: 'SIGN', lines: ['RUTA 3', 'MONTE LUNA → CIUDAD AZULONA'] },
    ],
  },

  gym: {
    name: 'GIMNASIO DE PEWTER',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXXXX',
      'X.............X',
      'X..X..XXX..X..X',
      'X.............X',
      'X.............X',
      'X..XXX...XXX..X',
      'X.............X',
      'X.............X',
      'XXXXXXXmXXXXXXX',
    ],
    warps: { '7,8': { to: 'pewter', x: 3.5, y: 8.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 3.5, y: 6.5, sprite: 'BOY', script: 'gymTrainer1' },
      { x: 11.5, y: 3.5, sprite: 'BOY', script: 'gymTrainer2' },
      { x: 7.5, y: 1.5, sprite: 'BROCK', script: 'brock' },
    ],
  },

  pewter_center: {
    name: 'CENTRO POKéMON',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXXXXXX',
      'XKK...........KKX',
      'X...X.......X...X',
      'X...X.......X...X',
      'X...............X',
      'X...............X',
      'XXXXXXXmXXXXXXXXX',
    ],
    warps: { '7,6': { to: 'pewter', x: 3.5, y: 4.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 8.5, y: 1.3, sprite: 'NURSE', script: 'nurse' },
      { x: 3.5, y: 4.5, sprite: 'BOY', lines: ['¡Brock es muy duro!', 'Usa POKéMON de Agua o Planta', 'si puedes.'],
        dark: ['Todo aquí huele a hospital.', 'Siempre igual.', 'Siempre igual.'] },
      { x: 3.5, y: 2.5, sprite: 'HEALMACHINE', lines: ['Una máquina de curación.', 'Zumba suavemente.'],
        dark: ['La máquina tiene manchas.', 'No son de óxido.'] },
      { x: 13.5, y: 2.5, sprite: 'PHONE', lines: ['Un teléfono público.', 'Nadie llama nunca.'],
        dark: ['El teléfono está descolgado.', 'Se oye respirar al otro lado.'] },
    ],
  },

  pewter_mart: {
    name: 'TIENDA POKéMON',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXXXX',
      'XKKKK---XKKKKKX',
      'X-------X-----X',
      'X.............X',
      'X.............X',
      'X.............X',
      'XXXXXXXmXXXXXXX',
    ],
    warps: { '7,6': { to: 'pewter', x: 9.5, y: 4.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 4.5, y: 2.5, sprite: 'CLERK', script: 'clerk' },
      { x: 11.5, y: 3.5, sprite: 'SHELF', lines: ['Estanterías bien surtidas.', 'Hay Pociones y Poké Balls.'],
        dark: ['Cajas vacías en las estanterías.', '¿Cuándo fue la última vez', 'que alguien compró algo?'] },
    ],
  },

  route3: {
    name: 'RUTA 3',
    outdoor: true,
    grid: [
      'TTTTTeeTTTTTT',
      'T...........T',
      'T.,,,,,.....T',
      'T.,,,,,..TT.T',
      'T........TT.T',
      'T...........T',
      'T.TT,,,,,...T',
      'T.TT,,,,,...T',
      'T...........T',
      'T.,,,,......T',
      'T.,,,,..TT..T',
      'T.......TT..T',
      'T...........T',
      'T.TT,,,,....T',
      'T.TT,,,,....T',
      'T...........T',
      'T...........T',
      'T...........T',
      'T...........T',
      'TTTTTeeTTTTTT',
    ],
    warps: {
      '5,0':  { to: 'mtmoon', x: 5.5, y: 18.5, ang: -Math.PI / 2 },
      '6,0':  { to: 'mtmoon', x: 6.5, y: 18.5, ang: -Math.PI / 2 },
      '5,19': { to: 'pewter', x: 5.5, y: 1.5,  ang: Math.PI / 2 },
      '6,19': { to: 'pewter', x: 6.5, y: 1.5,  ang: Math.PI / 2 },
    },
    encounters: {
      lv: [8, 14],
      table: [['PIDGEY', 25], ['RATTATA', 25], ['MANKEY', 20], ['JIGGLYPUFF', 15], ['SPEAROW', 15]],
    },
    npcs: [
      { x: 5.5, y: 3.5, sprite: 'BOY', script: 'route3Trainer1' },
      { x: 5.5, y: 9.5, sprite: 'GIRL', script: 'route3Trainer2' },
      { x: 7.5, y: 13.5, sprite: 'BOY', script: 'route3Trainer3' },
      { x: 3.5, y: 1.5, sprite: 'SIGN', lines: ['RUTA 3', 'CIUDAD PLATEADA → MONTE LUNA'] },
    ],
  },

  mtmoon: {
    name: 'MONTE LUNA',
    outdoor: false,
    grid: [
      'XXXXXeeXXXXXX',
      'X...........X',
      'X..X.....X..X',
      'X..X.....X..X',
      'X...........X',
      'X...........X',
      'X.XXX...XXX.X',
      'X...........X',
      'X...........X',
      'X..X.....X..X',
      'X..X.....X..X',
      'X...........X',
      'X...........X',
      'X.XXX...XXX.X',
      'X...........X',
      'X...........X',
      'X..X.....X..X',
      'X...........X',
      'X...........X',
      'XXXXXeeXXXXXX',
    ],
    warps: {
      '5,0':  { to: 'route4', x: 5.5, y: 9.5,  ang: -Math.PI / 2 },
      '6,0':  { to: 'route4', x: 6.5, y: 9.5,  ang: -Math.PI / 2 },
      '5,19': { to: 'route3', x: 5.5, y: 1.5,  ang: Math.PI / 2 },
      '6,19': { to: 'route3', x: 6.5, y: 1.5,  ang: Math.PI / 2 },
    },
    encounters: {
      lv: [8, 15],
      table: [['ZUBAT', 40], ['GEODUDE', 35], ['CLEFAIRY', 25]],
    },
    npcs: [
      { x: 5.5, y: 4.5, sprite: 'BOY', script: 'moonTrainer1' },
      { x: 5.5, y: 10.5, sprite: 'GIRL', script: 'moonTrainer2' },
      { x: 7.5, y: 15.5, sprite: 'BOY', script: 'moonTrainer3' },
      { x: 2.5, y: 7.5, sprite: 'FOSSIL', lines: ['Un fósil incrustado en la roca.', 'Parece un cuerno de hueso.', 'No puedes llevártelo.'],
        dark: ['No es un fósil.', 'Es un hueso.', 'No quieres saber de qué.'] },
      { x: 10.5, y: 12.5, sprite: 'SIGN', lines: ['Las paredes brillan', 'con una luz extraña.', 'Hay marcas de arañazos.'],
        dark: ['Las marcas van de arriba abajo.', 'Alguien contaba algo', 'en las paredes.'] },
    ],
  },

  route4: {
    name: 'RUTA 4',
    outdoor: true,
    grid: [
      'TTTTTeeTTTTTT',
      'T...........T',
      'T.,,,,,.....T',
      'T.,,,,,..TT.T',
      'T........TT.T',
      'T...........T',
      'T.TT,,,,,...T',
      'T.TT,,,,,...T',
      'T...........T',
      'T...........T',
      'TTTTTeeTTTTTT',
    ],
    warps: {
      '5,0':  { to: 'cerulean', x: 5.5, y: 11.5, ang: -Math.PI / 2 },
      '6,0':  { to: 'cerulean', x: 6.5, y: 11.5, ang: -Math.PI / 2 },
      '5,10': { to: 'mtmoon',   x: 5.5, y: 1.5,  ang: Math.PI / 2 },
      '6,10': { to: 'mtmoon',   x: 6.5, y: 1.5,  ang: Math.PI / 2 },
    },
    encounters: {
      lv: [10, 16],
      table: [['PIDGEY', 30], ['RATTATA', 25], ['MANKEY', 25], ['GOLDEEN', 20]],
    },
    npcs: [
      { x: 3.5, y: 5.5, sprite: 'BOY', script: 'route4Trainer1' },
      { x: 9.5, y: 7.5, sprite: 'GIRL', script: 'route4Trainer2' },
      { x: 5.5, y: 1.5, sprite: 'SIGN', lines: ['RUTA 4', 'MONTE LUNA ← CIUDAD AZULONA →'] },
    ],
  },

  cerulean: {
    name: 'CIUDAD AZULONA',
    outdoor: true,
    grid: [
      'TTTTTTTTTTTTTTTT',
      'T..............T',
      'T.BBBB.BBBB....T',
      'T.BDBB.BBDB....T',
      'T..............T',
      'T.BBBBBB.......T',
      'T.BBDBBB.......T',
      'T..............T',
      'T.....BBBB.BBBBT',
      'T.....BDBB.BBDBT',
      'T..............T',
      'T..............T',
      'TTTTTeeTTTTTTTTT',
    ],
    warps: {
      '3,3':  { to: 'crimehouse',      x: 4.5, y: 4.5, ang: -Math.PI / 2 },
      '7,3':  { locked: 'Está cerrado con llave.' },
      '4,6':  { to: 'cerulean_gym',    x: 7.5, y: 7.5, ang: -Math.PI / 2 },
      '7,9':  { to: 'cerulean_center', x: 7.5, y: 4.5, ang: -Math.PI / 2 },
      '13,9': { to: 'cerulean_mart',   x: 7.5, y: 4.5, ang: -Math.PI / 2 },
      '5,12': { to: 'route4', x: 5.5, y: 1.5, ang: Math.PI / 2 },
      '6,12': { to: 'route4', x: 6.5, y: 1.5, ang: Math.PI / 2 },
    },
    encounters: null,
    npcs: [
      { x: 1.5, y: 3.5, sprite: 'SIGN', lines: ['Casa de los JENKINS.', '¿Conoces a esta familia?'],
        dark: ['Casa de los JENKINS.', 'Tres personas.', 'Tres.'] },
      { x: 4.5, y: 7.5, sprite: 'SIGN', lines: ['GIMNASIO POKéMON', 'Líder: MISTY', 'Especialista en AGUA.'] },
      { x: 5.5, y: 10.5, sprite: 'SIGN', lines: ['CENTRO POKéMON', 'Curamos a tus POKéMON.'] },
      { x: 12.5, y: 10.5, sprite: 'SIGN', lines: ['TIENDA POKéMON', 'Todo para tu aventura.'] },
      { x: 10.5, y: 4.5, sprite: 'BOY', script: 'ceruleanBoy' },
      { x: 10.5, y: 7.5, sprite: 'GIRL', script: 'ceruleanGirl' },
    ],
  },

  crimehouse: {
    name: 'CASA JENKINS',
    outdoor: false,
    grid: [
      'XXXXXXXXX',
      'X.......X',
      'X.......X',
      'X.......X',
      'X.......X',
      'X.......X',
      'XXXXmXXXX',
    ],
    warps: { '4,6': { to: 'cerulean', x: 3.5, y: 4.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 2.5, y: 2.5, sprite: 'CORPSE', cond: f => !f.crimeHouseRevealed,
        lines: ['No se mueve.', 'Lleva tiempo sin moverse.'] },
      { x: 4.5, y: 3.5, sprite: 'CORPSE', cond: f => !f.crimeHouseRevealed,
        lines: ['...', '...'] },
      { x: 6.5, y: 4.5, sprite: 'CORPSE', cond: f => !f.crimeHouseRevealed,
        lines: ['Hay algo oscuro en el suelo.', 'No es sombra.'] },
      { x: 2.5, y: 2.5, sprite: 'BOY', cond: f => !!f.crimeHouseRevealed,
        lines: ['¡Hola! ¿Eres de por aquí?', '¡Bienvenido a CIUDAD AZULONA!'] },
      { x: 4.5, y: 3.5, sprite: 'GIRL', cond: f => !!f.crimeHouseRevealed,
        lines: ['¿Has visitado ya el GIMNASIO?', '¡MISTY es muy fuerte!'] },
      { x: 6.5, y: 4.5, sprite: 'MOM', cond: f => !!f.crimeHouseRevealed,
        lines: ['Pasa, pasa.', 'Te preparo algo si tienes hambre.', '¿Cuándo fue la última vez', 'que comiste de verdad?'] },
    ],
  },

  cerulean_gym: {
    name: 'GIMNASIO DE CERULEAN',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXXXXX',
      'X..............X',
      'X..WWWW..WWWW..X',
      'X..WWWW..WWWW..X',
      'X..............X',
      'X..WWWW..WWWW..X',
      'X..WWWW..WWWW..X',
      'X..............X',
      'XXXXXXXXmXXXXXXX',
    ],
    warps: { '8,8': { to: 'cerulean', x: 3.5, y: 7.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 4.5, y: 4.5, sprite: 'BOY', script: 'ceruleanGymTrainer1' },
      { x: 11.5, y: 4.5, sprite: 'BOY', script: 'ceruleanGymTrainer2' },
      { x: 8.5, y: 1.5, sprite: 'MISTY', script: 'misty' },
    ],
  },

  cerulean_center: {
    name: 'CENTRO POKéMON',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXXXXXX',
      'XKK...........KKX',
      'X...X.......X...X',
      'X...X.......X...X',
      'X...............X',
      'X...............X',
      'XXXXXXXmXXXXXXXXX',
    ],
    warps: { '7,6': { to: 'cerulean', x: 6.5, y: 10.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 8.5, y: 1.3, sprite: 'NURSE', script: 'nurse' },
      { x: 4.5, y: 4.5, sprite: 'BOY', lines: ['MISTY es increíblemente dura.', 'Sus POKéMON de agua son rápidos.', 'Ten muchas Pociones.'],
        dark: ['Llevo aquí dos semanas.', 'Dicen que la puerta norte', 'sigue cerrada.', '¿Qué pasó en esa casa?'] },
      { x: 3.5, y: 2.5, sprite: 'HEALMACHINE', lines: ['Una máquina de curación.', 'Zumba suavemente.'],
        dark: ['La máquina tiene manchas.', 'No son de óxido.'] },
      { x: 13.5, y: 2.5, sprite: 'PHONE', lines: ['Un teléfono público.', 'Nadie llama nunca.'],
        dark: ['El teléfono está descolgado.', 'Se oye respirar al otro lado.'] },
    ],
  },

  cerulean_mart: {
    name: 'TIENDA POKéMON',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXXXX',
      'XKKKK---XKKKKKX',
      'X-------X-----X',
      'X.............X',
      'X.............X',
      'X.............X',
      'XXXXXXXmXXXXXXX',
    ],
    warps: { '7,6': { to: 'cerulean', x: 12.5, y: 10.4, ang: Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 4.5, y: 2.5, sprite: 'CLERK', script: 'clerk' },
      { x: 11.5, y: 3.5, sprite: 'SHELF', lines: ['Súper Pociones disponibles.', 'Restauran 50 PS.'],
        dark: ['Las Súper Pociones', 'son para uso externo.', '¿Qué haces?'] },
    ],
  },

  sewers_a: {
    name: 'ALCANTARILLADO - A',
    outdoor: false,
    grid: [
      'XXXXXXXXXXXXX',
      'X...........X',
      'X.XXX.......X',
      'X.X.........X',
      'X.X.XXXXXXX.X',
      'X...........X',
      'X...XXXXX...X',
      'X...........X',
      'X.XXXXX.....X',
      'X...........X',
      'X...........X',
      'X.......XXX.X',
      'X...........X',
      'X...........X',
      'XXXXXXeXXXXXX',
    ],
    warps: { '6,14': { to: 'sewers_b', x: 6.5, y: 1.5, ang: -Math.PI / 2 } },
    encounters: null,
    npcs: [
      { x: 3.5, y: 5.5, sprite: 'DOCTOR', script: 'sewerOrderly' },
      { x: 8.5, y: 8.5, sprite: 'PATIENT', lines: ['Psst.', 'Sigue recto.', 'No mires hacia atrás.'] },
      { x: 2.5, y: 11.5, sprite: 'CORPSE', lines: ['...', '...'] },
    ],
  },

  sewers_b: {
    name: 'ALCANTARILLADO - B',
    outdoor: false,
    grid: [
      'XXXXXXeXXXXXX',
      'X...........X',
      'X.......XXX.X',
      'X...........X',
      'X.XXXXXXX...X',
      'X...........X',
      'X...XXXXX...X',
      'X...........X',
      'X.XXX.......X',
      'X...........X',
      'X...........X',
      'X.......XXX.X',
      'X...........X',
      'X...........X',
      'XXXXXXeXXXXXX',
    ],
    warps: {
      '6,0':  { to: 'sewers_a',    x: 6.5, y: 13.5, ang: Math.PI / 2 },
      '6,14': { to: 'sewers_exit', x: 6.5, y: 1.5,  ang: -Math.PI / 2 },
    },
    encounters: null,
    npcs: [
      { x: 9.5, y: 4.5, sprite: 'DOCTOR', script: 'sewerOrderly' },
      { x: 9.5, y: 6.5, sprite: 'PATIENT', lines: ['Hay dos guardias más', 'en el tramo final.', 'Si llegaste hasta aquí...', 'puedes.'] },
      { x: 5.5, y: 10.5, sprite: 'CORPSE', lines: ['...'] },
      { x: 9.5, y: 12.5, sprite: 'DOCTOR', script: 'sewerOrderly' },
    ],
  },

  sewers_exit: {
    name: 'SALIDA',
    outdoor: false,
    grid: [
      'XXXXXXeXXXXXX',
      'X...........X',
      'X...........X',
      'X...........X',
      'X...........X',
      'X...........X',
      'X...........X',
      'X...........X',
      'X...........X',
      'XXXXXXXXXXXXX',
    ],
    warps: {
      '6,0': { to: 'sewers_b', x: 6.5, y: 13.5, ang: Math.PI / 2 },
    },
    encounters: null,
    npcs: [
      { x: 6.5, y: 4.5, sprite: 'DOCTOR', lines: ['...', 'Deberías volver.', 'Tu habitación está en el ala norte.'] },
      { x: 6.5, y: 7.5, sprite: 'BOY', script: 'sewersExit' },
    ],
  },

};

const WALL_TILES = 'TBDFWXLK';
const FLOOR_TILES = '.,:-me';

function tileAt(map, x, y) {
  const g = MAPS[map].grid;
  if (y < 0 || y >= g.length || x < 0 || x >= g[y].length) return 'T';
  return g[y][x];
}
function isWallTile(c) { return WALL_TILES.includes(c); }
